### ISSUE TITLE
[clarification] Gemini Insight output is blank

### ISSUE THREAD

**Issue by dennysrega1ado** [Juventin/looker_gemini_insight#1]
Am I missing something?

0. Why your URL is hardcoded in looker_gemini_insight.js?
1. ~Is there a way to verify the app is running correctly?~ Yes, you will get 'Hello, World!' message on `https://<YOUR_CLOUD_RUN_URL>.run.app/`. 
2. ~Does the app allow unauthenticated invocations?~  Yes, since you are using AllUsers as the principal type
3. ~Is the parameter in `manifest.lkml` right?~  No, it should be `"url: "https://<YOUR_CLOUD_RUN_URL>.run.app/source.js"`
4. Is there a way to show Looker logs? Do you know how I can troubleshoot the custom viz in Looker?
5. How can we automatically roll back (clan up) the resources created by this repo?

Nothing shows up in Looker and I don't see any request in looker-gemini-insight logs.
<img width="1367" alt="image" src="https://github.com/user-attachments/assets/d518184d-2ca8-4c3d-806b-aa711e72e4c1">

**Comment by Juventin** [comment]
Hello,
Thanks for your issue

Your questions have been added to the FAQ section of the README

> Why your URL is hardcoded in looker_gemini_insight.js?

This has been fixed with the latest commits.

> Is there a way to show Looker logs? Do you know how I can troubleshoot the custom viz in Looker?

Not that I know of, unfortunately. But you can get the server logs on GCP using the Cloud Run Logging.

> How can we automatically roll back (clan up) the resources created by this repo?

Terraform will be implemented soon :)
In the meantime, the only service that is deployed should be the looker-gemini-insight Cloud Run and its docker image in the Artifact Registry.
